# https://www.alibabacloud.com/blog/how-to-build-nginx-from-source-on-ubuntu-20-04-lts_597793

install:
  assertReturnCode: 0
  tools:
  - [ apt install -y net-tools ]
  dependencies:
  - [ apt install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev libxml2 libxml2-dev uuid-dev ]
  configure:
  - [ ./auto/configure ]
  make:
  - [ make ]
  make_install:
  - [ make install ]
  nginx:
  - [ /usr/local/nginx/sbin/nginx ]

netstat:
  assertStdoutEqual: "2"
  listen:
  - [ netstat -nlp | grep LISTEN | wc -l ]
  
curl:
  assertReturnCode: 0
  assertStderr: False
  assertStdoutContains: "200 OK"
  localhost:
  - [ curl -sI http://127.0.0.1 ]
