# https://www.alibabacloud.com/blog/how-to-build-nginx-from-source-on-ubuntu-20-04-lts_597793

install:
  assertReturnCode: 0
  dependencies:
  - [ apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev libxml2 libxml2-dev uuid-dev ]
  configure:
  - [ ./auto/configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic --modules-path=/etc/nginx/modules --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module ]
  configure2:
  - [ ./auto/configure --without-http_empty_gif_module ]
  make:
  - [ make ]
  make_install:
  - [ make install ]
  nginx:
  - [ nginx ]

output:
  assertStdout: False
  whereis:
  - [ whereis nginx ]
  ls:
  - [ ls -lR ]
