# https://www.alibabacloud.com/blog/how-to-build-nginx-from-source-on-ubuntu-20-04-lts_597793

install:
  assertReturnCode: 0
  tools:
  - [ apt install -y netstat ]
  dependencies:
  - [ apt install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev libxml2 libxml2-dev uuid-dev ]
  #configure:
  #- [ ./auto/configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic --modules-path=/etc/nginx/modules --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module ]
  configure2:
  - [ ./configure ]
  make:
  - [ make ]
  make_install:
  - [ make install ]
  nginx:
  - [ /usr/local/nginx/sbin/nginx ]

output:
  assertReturnCode: 0
  assertStdout: False
  assertStderr: False
  curl:
  - [ curl -I http://127.0.0.1 ]
  netstat:
  - [ netstat -nlp ]
